---
# Author: David HEURTEVENT
# Date : 2024-02-25
# License: MIT

# tasks file for import_script

# Import a plain text configuration script

- name: "The source script must be present"
  ansible.builtin.file:
    path: "{{ source_folder }}/{{ script_name }}"
    state: file

- name: "Copy the script to the Mikrotik device"
  ansible.builtin.copy:
    src: "{{ source_folder }}/{{ script_name }}"
    dest: "{{ script_name }}"

- name: "Import the script file"
  community.routeros.command:
    commands: "/import file={{ script_name }}"