---
# Author: David HEURTEVENT
# Date : 2024-02-25
# License: MIT

# tasks file for ip_address_print

# Print the list of IPv4 addresses

- name: 'Prepare command'
  ansible.builtin.set_fact:
    cmd: "/ip address print"

- name: "Run {{ cmd }} on {{ ansible_host }}"
  community.network.routeros_command:
    commands: "[:put ([{{ cmd }}])]"
  register: output

- name: 'Store fact'
  ansible.builtin.set_fact:
    routerboard_fact: "{{ output.stdout_lines[0] | list }}"
  no_log: true

- name: 'Display the current list of IPv4 addresses'
  ansible.builtin.debug:
    msg: "{{ routerboard_fact }}"