---
# (c) Copyright: David HEURTEVENT, 2023
# License: MIT

# tasks file for system_clock_print

# Display the system clock 
#https://help.mikrotik.com/docs/display/ROS/Clock

- name: 'Prepare command'
  ansible.builtin.set_fact:
    cmd: "/system clock print"

- name: "Run {{ cmd }} on {{ ansible_host }}"
  community.network.routeros_command:
    commands: "[:put ([{{ cmd }}])]"
  register: output

- name: 'Store fact'
  ansible.builtin.set_fact:
    routerboard_fact: "{{ routerboard_fact | default([]) | combine ( { item.split(':')[0] | trim : item.split(':')[1] | trim }) }}"
  with_items: "{{ output.stdout_lines[0] | list }}"

- name: 'Display the system clock'
  ansible.builtin.debug:
    msg: "{{ routerboard_fact }}"

