---
# Author: David HEURTEVENT
# Date : 2024-02-25
# License: MIT

# tasks file for user_print

# Print the list of users

- name: 'Prepare command'
  ansible.builtin.set_fact:
    cmd: "/user print"

- name: "Run {{ cmd }} on {{ ansible_host }}"
  community.network.routeros_command:
    commands: "[:put ([{{ cmd }}])]"
  register: output

- name: 'Store user list fact'
  ansible.builtin.set_fact:
    routerboard_fact: "{{ output.stdout_lines[0] | list }}"
  no_log: true

- name: 'Display the current list of users'
  ansible.builtin.debug:
    msg: "{{ routerboard_fact }}"