---
# (c) Copyright: David HEURTEVENT, 2023
# License: MIT

# tasks file for system_resource_print

# Gather and display the current system resources
#https://help.mikrotik.com/docs/display/ROS/Resource

- name: 'Prepare command'
  ansible.builtin.set_fact:
    cmd: "/system resource print"

- name: "Run {{ cmd }} on {{ ansible_host }}"
  community.network.routeros_command:
    commands: "[:put ([{{ cmd }}])]"
  register: output

- name: 'Store fact'
  ansible.builtin.set_fact:
    routerboard_fact: "{{ routerboard_fact | default([]) | combine ( { item.split(':')[0] | trim : item.split(':')[1] | trim }) }}"
  with_items: "{{ output.stdout_lines[0] | list }}"
  no_log: true

- name: 'Display the current resource'
  ansible.builtin.debug:
    msg: "{{ routerboard_fact }}"