---
# Author: David HEURTEVENT
# Date : 2024-02-25
# License: MIT

# defaults file for export_script
# See https://docs.ansible.com/ansible/latest/collections/community/routeros/facts_module.html#ansible-collections-community-routeros-facts-module
subset: 'config'

target_filepath: '/tmp/backup.rsc'
temp_file: 'temp_backup_ansible.rsc'