---
# Author: David HEURTEVENT
# Date : 2024-02-25
# License: MIT

# tasks file for export_backup_encrypted

# Export the configuration as an encrypted backup

- name: "Backup file should be absent in local filesystem"
  ansible.builtin.file:
    path: "{{ target_filepath }}"
    state: absent

- name: "Export the unencrypted configuration on the Mikrotik device"
  community.routeros.command:
    commands: "/system backup save name={{ temp_file }} password={{ password }}"

- name: "Download the backup"
  ansible.netcommon.net_get:
    src: "{{ temp_file }}"
    dest: "{{ target_filepath }}"
    protocol: sftp

- name: "Backup should be present in local filesystem"
  ansible.builtin.file:
    path: "{{ target_filepath }}"
    state: file

- name: "Delete backup file on the Mikrotik device"
  community.routeros.command:
    commands: "/file remove {{ temp_file }}"