---
# Author: David HEURTEVENT
# Date : 2024-02-25
# License: MIT

# tasks file for export_backup_encrypted

# Export the configuration as an encrypted backup

- name: "Backup file should be absent in local filesystem"
  ansible.builtin.file:
    path: "{{ export_folder }}/{{ script_name }}"
    state: absent

- name: "Export the unencrypted configuration on the Mikrotik device to {{ script_name }}"
  community.routeros.command:
    commands: "/system backup save name={{ script_name }} password={{ password }}"

- name: "Download the backup"
  ansible.netcommon.net_get:
    src: "{{ script_name }}"
    dest: "{{ export_folder }}/{{ script_name }}"
    protocol: sftp

- name: "Backup should be present in local filesystem"
  ansible.builtin.file:
    path: "{{ export_folder }}/{{ script_name }}"
    state: file

- name: "Delete backup file on the Mikrotik device"
  community.routeros.command:
    commands: "/file remove {{ script_name }}"