---
# (c) Copyright: David HEURTEVENT, 2023
# License: Apache License, Version 2.0

# tasks file for get_facts

- name: "Collect {{ subset }} facts from {{ ansible_host }}"
  community.routeros.facts:
    gather_subset: "{{ subset }}"
  register: ansible_facts

- set_fact:
    ansible_facts: "{{ ansible_facts }}"