---
# Author: David HEURTEVENT
# Date: 2024-02-25
# License: MIT

# Print bridge interface details

- hosts: all
  become: true
  tasks:

  - name: print bridge interface details
    import_role: 
      name: interface_print
    vars:
      interface: 'bridge'